load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("secure_pipes")

cpp_library(
    name = "batch_signature_async_self_cert",
    headers = [
        "BatchSignatureAsyncSelfCert.h",
    ],
    exported_deps = [
        "//fizz/experimental/batcher:batcher",
        "//fizz/experimental/crypto:batch_signature",
        "//fizz/experimental/protocol:batch_signature_types",
        "//fizz/server:async_self_cert",
        "//fizz/server:protocol",
    ],
)
