load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("secure_pipes")

cpp_library(
    name = "mocks",
    headers = [
        "Mocks.h",
    ],
    exported_deps = [
        "//fizz/crypto/exchange:async_key_exchange",
        "//fizz/crypto/exchange:key_exchange",
        "//folly/portability:gmock",
    ],
)

cpp_unittest(
    name = "x25519",
    srcs = [
        "X25519KeyExchangeTest.cpp",
    ],
    deps = [
        "//fizz/crypto/exchange:x25519",
        "//folly:range",
        "//folly:string",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "HybridExchange",
    srcs = [
        "HybridKeyExchangeTest.cpp",
    ],
    deps = [
        ":mocks",
        "//fizz/crypto/exchange:hybrid_key_exchange",
        "//folly/portability:gtest",
    ],
)
