load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("secure_pipes")

cpp_library(
    name = "batch_signature_factory",
    headers = [
        "BatchSignatureFactory.h",
    ],
    exported_deps = [
        "//fizz/experimental/client:batch_signature_peer_cert",
        "//fizz/protocol:factory",
    ],
)

cpp_library(
    name = "batch_signature_types",
    srcs = [
        "BatchSignatureTypes.cpp",
    ],
    headers = [
        "BatchSignatureTypes.h",
    ],
    exported_deps = [
        "//fizz/backend:openssl",
        "//fizz/crypto:hmac_sha256",
        "//fizz/record:record",
    ],
)
