load(
    "@fbsource//xplat/security/lionhead:defs.bzl",
    "EXTERNAL_USERS",
    "Metadata",
    "Severity",
)
load("//security/lionhead/harnesses:defs.bzl", "cpp_lionhead_harness")

oncall("secure_pipes")

cpp_lionhead_harness(
    name = "fizz_aead_encrypt_fuzzer",
    srcs = ["AeadFuzzer.cpp"],
    context_task = "T144013895",
    ftest_name = ("AeadFuzzer", "Encrypt"),
    metadata = Metadata(
        exposure = EXTERNAL_USERS,
        project = "oncall_secure_pipes",
        severity_denial_of_service = Severity.FILE_SECURITY_TASK,
        severity_service_takeover = Severity.FILE_SECURITY_TASK,
    ),
    deps = [
        "fbsource//third-party/googletest:gtest",
        "fbsource//xplat/security/lionhead/utils/lib_ftest:lib",
        "//fizz/crypto/test:TestUtil",
    ],
)

cpp_lionhead_harness(
    name = "fizz_aead_inplace_encrypt_fuzzer",
    srcs = ["AeadFuzzer.cpp"],
    context_task = "T144013895",
    ftest_name = ("AeadFuzzer", "InplaceEncrypt"),
    metadata = Metadata(
        exposure = EXTERNAL_USERS,
        project = "oncall_secure_pipes",
        severity_denial_of_service = Severity.FILE_SECURITY_TASK,
        severity_service_takeover = Severity.FILE_SECURITY_TASK,
    ),
    deps = [
        "fbsource//third-party/googletest:gtest",
        "fbsource//xplat/security/lionhead/utils/lib_ftest:lib",
        "//fizz/crypto/test:TestUtil",
    ],
)

cpp_lionhead_harness(
    name = "fizz_aead_decrypt_fuzzer",
    srcs = ["AeadFuzzer.cpp"],
    context_task = "T144013895",
    ftest_name = ("AeadFuzzer", "Decrypt"),
    metadata = Metadata(
        exposure = EXTERNAL_USERS,
        project = "oncall_secure_pipes",
        severity_denial_of_service = Severity.FILE_SECURITY_TASK,
        severity_service_takeover = Severity.FILE_SECURITY_TASK,
    ),
    deps = [
        "fbsource//third-party/googletest:gtest",
        "fbsource//xplat/security/lionhead/utils/lib_ftest:lib",
        "//fizz/crypto/test:TestUtil",
    ],
)
