load("@fbcode//dependencies/buck:wdl.bzl", "wdls")
# @fb-only[end= ]: load("@fbcode//registry:defs.bzl", "rpm")
load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:export_files.bzl", "export_files")
load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")
load(":defs.bzl", "fizz_cpp_library")
load(":fizzy_defs.bzl", "fizzy_library")

oncall("secure_pipes")

fizzy_library(
    # @autodeps-skip
    name = "fizzy",
)

fizz_cpp_library(
    name = "config",
    headers = select({
        "DEFAULT": select({
            "DEFAULT": {"fizz-config.h": "//:fizz-config.h"}, # @oss-only
            # @fb-only[end= ]: "DEFAULT": {"fizz-config.h": "facebook/fizz-config-xplat.h"},
            # @fb-only[end= ]: "ovr_config//runtime:fbcode": {"fizz-config.h": "facebook/fizz-config-fbcode.h"},
        }),
        # @fb-only[end= ]: "fbsource//xplat/fizz/constraints:profile[mnscrypto-only]": {"fizz-config.h": "facebook/fizz-config-mnscrypto-only.h"},
        # @fb-only[end= ]: "fbsource//xplat/fizz/constraints:profile[xplat]": {"fizz-config.h": "facebook/fizz-config-xplat.h"},
    }),
    labels = wdls.FIZZ,
    # Each individual tunable should have its own select().
    propagated_pp_flags = select({
        "DEFAULT": ["-DFIZZ_HAVE_OQS"],
        "fbsource//xplat/fizz/constraints:oqs[disabled]": [],
    }),
)

fbcode_target(
    _kind = export_files,
    files = [
        "cmake/CheckAtomic.cmake",
        "cmake/FindGMock.cmake",
        "cmake/FindLibevent.cmake",
        "cmake/FindLibrt.cmake",
        "cmake/fizz-config.cmake.in",
        "cmake/FizzOptions.cmake",
        "CMakeListsForBuck2.txt",
        "fizz-config.h.in",
    ],
)

# @fb-only[end= ]: rpm.builder(
    # @fb-only[end= ]: name = "fb-fizz",
    # @fb-only[end= ]: autoclean_keep_versions = 200,
    # @fb-only[end= ]: configurations = [
        # @fb-only[end= ]: rpm.configuration(
            # @fb-only[end= ]: arch = "x86_64",
        # @fb-only[end= ]: ),
        # @fb-only[end= ]: rpm.configuration(
            # @fb-only[end= ]: arch = "aarch64",
        # @fb-only[end= ]: ),
    # @fb-only[end= ]: ],
    # @fb-only[end= ]: features = [
        # @fb-only[end= ]: rpm.install(
            # @fb-only[end= ]: src = "fbcode//fizz/tool:fizz",
            # @fb-only[end= ]: dst = "/usr/local/bin/fizz",
        # @fb-only[end= ]: ),
    # @fb-only[end= ]: ],
    # @fb-only[end= ]: summary = "Fizz TLS library command-line tool",
# @fb-only[end= ]: )

# @fb-only[end= ]: fb_native.export_file(
    # @fb-only[end= ]: name = "src-tree",
    # @fb-only[end= ]: src = ".",
    # @fb-only[end= ]: mode = "reference",
    # @fb-only[end= ]: visibility = ["PUBLIC"],
# @fb-only[end= ]: )
