# (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.
FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_CONTEXT_HEADERS = [
    "extensions/tokenbinding/TokenBindingContext.h",
]

FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_SERVER_EXTENSION_HEADERS = [
    "extensions/tokenbinding/TokenBindingServerExtension.h",
]

FIZZ_SERVER_ASYNC_FIZZ_SERVER_HEADERS = [
    "server/AsyncFizzServer-inl.h",
    "server/AsyncFizzServer.h",
]

FIZZ_SERVER_TICKET_TYPES_HEADERS = [
    "server/TicketTypes.h",
]

FIZZ_PROTOCOL_DEFAULT_CERTIFICATE_VERIFIER_HEADERS = [
    "protocol/DefaultCertificateVerifier.h",
]

FIZZ_PROTOCOL_DEFAULT_CERTIFICATE_VERIFIER_SOURCES = [
    "protocol/DefaultCertificateVerifier.cpp",
]

FIZZ_SERVER_FIZZ_SERVER_CONTEXT_HEADERS = [
    "server/FizzServerContext.h",
]

FIZZ_UTIL_FIZZ_UTIL_HEADERS = [
    "util/FizzUtil.h",
]

FIZZ_UTIL_FIZZ_UTIL_SOURCES = [
    "util/FizzUtil.cpp",
]

FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_HEADERS = [
    "extensions/tokenbinding/Types.h",
]

FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_SOURCES = [
    "extensions/tokenbinding/Types.cpp",
]

FIZZ_RECORD_RECORD_HEADERS = [
    "record/Extensions-inl.h",
    "record/Extensions.h",
    "record/Types-inl.h",
    "record/Types.h",
]

FIZZ_RECORD_RECORD_SOURCES = [
    "record/Types.cpp",
]

FIZZ_SERVER_NEGOTIATOR_HEADERS = [
    "server/Negotiator.h",
]

FIZZ_SERVER_SERVER_EXTENSIONS_HEADERS = [
    "server/ServerExtensions.h",
]

FIZZ_PROTOCOL_ASYNC_FIZZ_BASE_HEADERS = [
    "protocol/AsyncFizzBase.h",
]

FIZZ_PROTOCOL_ASYNC_FIZZ_BASE_SOURCES = [
    "protocol/AsyncFizzBase.cpp",
]

FIZZ_PROTOCOL_EXPORTER_HEADERS = [
    "protocol/Exporter.h",
]

FIZZ_PROTOCOL_EXPORTER_SOURCES = [
    "protocol/Exporter.cpp",
]

FIZZ_SERVER_FIZZ_SERVER_HEADERS = [
    "server/FizzServer-inl.h",
    "server/FizzServer.h",
]

FIZZ_SERVER_FIZZ_SERVER_SOURCES = [
    "server/FizzServer.cpp",
]

FIZZ_SERVER_PROTOCOL_HEADERS = [
    "server/Actions.h",
    "server/ServerProtocol.h",
    "server/State.h",
]

FIZZ_SERVER_PROTOCOL_SOURCES = [
    "server/ServerProtocol.cpp",
    "server/State.cpp",
]

FIZZ_CRYPTO_AEAD_EVPCIPHER_HEADERS = [
    "backend/openssl/crypto/aead/AESGCM128.h",
    "backend/openssl/crypto/aead/AESGCM256.h",
    "backend/openssl/crypto/aead/AESOCB128.h",
    "backend/openssl/crypto/aead/ChaCha20Poly1305.h",
    "backend/openssl/crypto/aead/OpenSSLEVPCipher-inl.h",
    "backend/openssl/crypto/aead/OpenSSLEVPCipher.h",
]

FIZZ_CRYPTO_AEAD_EVPCIPHER_SOURCES = [
    "backend/openssl/crypto/aead/OpenSSLEVPCipher.cpp",
]

FIZZ_CRYPTO_HKDF_HEADERS = [
    "crypto/Hkdf.h",
]

FIZZ_CRYPTO_HKDF_SOURCES = [
    "crypto/Hkdf.cpp",
]

FIZZ_PROTOCOL_TYPES_HEADERS = [
    "protocol/Types.h",
]

FIZZ_PROTOCOL_TYPES_SOURCES = [
    "protocol/Types.cpp",
]

FIZZ_SERVER_AEAD_TICKET_CIPHER_HEADERS = [
    "server/AeadTicketCipher.h",
]

FIZZ_SERVER_TICKET_CODEC_HEADERS = [
    "server/TicketCodec-inl.h",
    "server/TicketCodec.h",
]

FIZZ_SERVER_TICKET_CODEC_SOURCES = [
    "server/TicketCodec.cpp",
]

FIZZ_PROTOCOL_CERTIFICATE_VERIFIER_HEADERS = [
    "protocol/CertificateVerifier.h",
]

FIZZ_PROTOCOL_CERTIFICATE_HEADERS = [
    "protocol/Certificate-inl.h",
    "protocol/Certificate.h",
]

FIZZ_PROTOCOL_CERTIFICATE_SOURCES = [
    "protocol/Certificate.cpp",
]

FIZZ_PROTOCOL_CLOCK_SYSTEM_CLOCK_HEADERS = [
    "protocol/clock/SystemClock.h",
]

FIZZ_PROTOCOL_CLOCK_SYSTEM_CLOCK_SOURCES = [
    "protocol/clock/SystemClock.cpp",
]

FIZZ_PROTOCOL_OPENSSL_FACTORY_HEADERS = [
    "backend/openssl/OpenSSLFactory.h",
]

FIZZ_SERVER_CERT_MANAGER_HEADERS = [
    "server/CertManager.h",
]

FIZZ_SERVER_CERT_MANAGER_SOURCES = [
    "server/CertManager.cpp",
]

FIZZ_SERVER_COOKIE_CIPHER_HEADERS = [
    "server/CookieCipher.h",
]

FIZZ_SERVER_COOKIE_CIPHER_SOURCES = [
    "server/CookieCipher.cpp",
]

FIZZ_SERVER_AEAD_COOKIE_CIPHER_HEADERS = [
    "server/AeadCookieCipher.h",
]

FIZZ_SERVER_AEAD_COOKIE_CIPHER_SOURCES = [
    "server/AeadCookieCipher.cpp",
]

FIZZ_SERVER_REPLAY_CACHE_HEADERS = [
    "server/ReplayCache.h",
]

FIZZ_SERVER_REPLAY_CACHE_SOURCES = [
    "server/ReplayCache.cpp",
]

FIZZ_SERVER_TICKET_CIPHER_HEADERS = [
    "server/TicketCipher.h",
]

FIZZ_PROTOCOL_KEY_SCHEDULER_HEADERS = [
    "protocol/KeyScheduler.h",
]

FIZZ_PROTOCOL_KEY_SCHEDULER_SOURCES = [
    "protocol/KeyScheduler.cpp",
]

FIZZ_CRYPTO_KEY_DERIVATION_HEADERS = [
    "crypto/KeyDerivation.h",
]

FIZZ_CRYPTO_KEY_DERIVATION_SOURCES = [
    "crypto/KeyDerivation.cpp",
]

FIZZ_PROTOCOL_FACTORY_HEADERS = [
    "protocol/Factory.h",
]

FIZZ_PROTOCOL_FIZZ_BASE_HEADERS = [
    "protocol/FizzBase-inl.h",
    "protocol/FizzBase.h",
]

FIZZ_CRYPTO_UTILS_HEADERS = [
    "crypto/Utils.h",
]

FIZZ_CRYPTO_UTILS_SOURCES = [
    "crypto/Utils.cpp",
]

FIZZ_PROTOCOL_ACTIONS_HEADERS = [
    "protocol/Actions.h",
]

FIZZ_PROTOCOL_PARAMS_HEADERS = [
    "protocol/Params.h",
]

FIZZ_PROTOCOL_PROTOCOL_HEADERS = [
    "protocol/Protocol.h",
]

FIZZ_PROTOCOL_STATE_MACHINE_HEADERS = [
    "protocol/StateMachine-inl.h",
    "protocol/StateMachine.h",
]

FIZZ_RECORD_PLAINTEXT_RECORD_LAYER_HEADERS = [
    "record/PlaintextRecordLayer.h",
]

FIZZ_RECORD_PLAINTEXT_RECORD_LAYER_SOURCES = [
    "record/PlaintextRecordLayer.cpp",
]

FIZZ_RECORD_RECORD_LAYER_HEADERS = [
    "record/RecordLayer.h",
]

FIZZ_RECORD_RECORD_LAYER_SOURCES = [
    "record/RecordLayer.cpp",
]

FIZZ_SERVER_ASYNC_SELF_CERT_HEADERS = [
    "server/AsyncSelfCert.h",
]

FIZZ_SERVER_RESUMPTION_STATE_HEADERS = [
    "server/ResumptionState.h",
]

FIZZ_UTIL_WORKAROUNDS_HEADERS = [
    "util/Workarounds.h",
]

FIZZ_CRYPTO_AEAD_AEAD_HEADERS = [
    "crypto/aead/Aead.h",
]

FIZZ_CRYPTO_AEAD_IOBUF_HEADERS = [
    "crypto/aead/IOBufUtil.h",
]

FIZZ_CRYPTO_AEAD_IOBUF_SOURCES = [
    "crypto/aead/IOBufUtil.cpp",
]

FIZZ_SERVER_TOKEN_CIPHER_HEADERS = [
    "server/TokenCipher.h",
]

FIZZ_SERVER_AEAD_TOKEN_CIPHER_HEADERS = [
    "server/AeadTokenCipher.h",
]

FIZZ_SERVER_AEAD_TOKEN_CIPHER_SOURCES = [
    "server/AeadTokenCipher.cpp",
]

FIZZ_CRYPTO_SIGNATURE_SIGNATURE_HEADERS = [
    "backend/openssl/crypto/signature/Signature-inl.h",
    "backend/openssl/crypto/signature/Signature.h",
]

FIZZ_CRYPTO_SIGNATURE_SIGNATURE_SOURCES = [
    "backend/openssl/crypto/signature/Signature.cpp",
]

FIZZ_PROTOCOL_CLOCK_CLOCK_HEADERS = [
    "protocol/clock/Clock.h",
]

FIZZ_CRYPTO_HMAC_SHA256_HEADERS = [
    "crypto/Sha256.h",
]

FIZZ_CRYPTO_HMAC_SHA256_SOURCES = [
    "crypto/Sha256.cpp",
]

FIZZ_CRYPTO_HMAC_SHA384_HEADERS = [
    "crypto/Sha384.h",
]

FIZZ_CRYPTO_HMAC_SHA384_SOURCES = [
    "crypto/Sha384.cpp",
]

FIZZ_CRYPTO_HMAC_SHA512_HEADERS = [
    "crypto/Sha512.h",
]

FIZZ_CRYPTO_HMAC_SHA512_SOURCES = [
    "crypto/Sha512.cpp",
]

FIZZ_PROTOCOL_HANDSHAKE_CONTEXT_HEADERS = [
    "protocol/HandshakeContext-inl.h",
    "protocol/HandshakeContext.h",
]

FIZZ_CRYPTO_EXCHANGE_EXCHANGE_HEADERS = [
    "backend/openssl/crypto/exchange/OpenSSLKeyExchange-inl.h",
    "backend/openssl/crypto/exchange/OpenSSLKeyExchange.h",
]

FIZZ_CRYPTO_EXCHANGE_KEY_EXCHANGE_HEADERS = [
    "crypto/exchange/KeyExchange.h",
]

FIZZ_CRYPTO_EXCHANGE_X25519_HEADERS = [
    "crypto/exchange/X25519.h",
]

FIZZ_CRYPTO_EXCHANGE_X25519_SOURCES = [
    "crypto/exchange/X25519.cpp",
]

FIZZ_CRYPTO_RANDOM_HEADERS = [
    "crypto/RandomGenerator.h",
]

FIZZ_RECORD_ENCRYPTED_RECORD_LAYER_HEADERS = [
    "record/EncryptedRecordLayer.h",
]

FIZZ_RECORD_ENCRYPTED_RECORD_LAYER_SOURCES = [
    "record/EncryptedRecordLayer.cpp",
]

FIZZ_RECORD_BUF_AND_PADDING_POLICY_HEADERS = [
    "record/BufAndPaddingPolicy.h",
]

FIZZ_RECORD_BUF_AND_PADDING_POLICY_SOURCES = [
    "record/BufAndPaddingPolicy.cpp",
]

FIZZ_CLIENT_PSK_SERIALIZATION_HEADERS = [
    "client/PskSerializationUtils.h",
]

FIZZ_CLIENT_PSK_SERIALIZATION_SOURCES = [
    "client/PskSerializationUtils.cpp",
]

FIZZ_CLIENT_CLIENT_EXTENSIONS_HEADERS = [
    "client/ClientExtensions.h",
]

FIZZ_CLIENT_PSK_CACHE_HEADERS = [
    "client/PskCache.h",
]

FIZZ_PROTOCOL_EVENTS_HEADERS = [
    "protocol/Events.h",
]

FIZZ_PROTOCOL_EVENTS_SOURCES = [
    "protocol/Events.cpp",
]

FIZZ_BACKEND_BACKEND_HEADERS = [
    "backend/openssl/OpenSSL.h",
]

FIZZ_CRYPTO_OPENSSL_OPENSSL_HEADERS = [
    "backend/openssl/crypto/OpenSSL.h",
    "backend/openssl/crypto/OpenSSLKeyUtils.h",
]

FIZZ_CRYPTO_OPENSSL_OPENSSL_SOURCES = [
    "backend/openssl/crypto/OpenSSLKeyUtils.cpp",
]

FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_CLIENT_EXTENSION_HEADERS = [
    "extensions/tokenbinding/TokenBindingClientExtension.h",
]

FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_CLIENT_EXTENSION_SOURCES = [
    "extensions/tokenbinding/TokenBindingClientExtension.cpp",
]

FIZZ_CLIENT_EARLY_DATA_REJECTION_HEADERS = [
    "client/EarlyDataRejectionPolicy.h",
]

FIZZ_CLIENT_EARLY_DATA_REJECTION_SOURCES = [
    "client/EarlyDataRejectionPolicy.cpp",
]

FIZZ_CLIENT_PROTOCOL_HEADERS = [
    "client/ClientProtocol.h",
]

FIZZ_CLIENT_PROTOCOL_SOURCES = [
    "client/ClientProtocol.cpp",
]

FIZZ_CLIENT_ACTIONS_HEADERS = [
    "client/Actions.h",
]

FIZZ_CLIENT_FIZZ_CLIENT_CONTEXT_HEADERS = [
    "client/FizzClientContext.h",
]

FIZZ_CLIENT_STATE_HEADERS = [
    "client/State.h",
]

FIZZ_CLIENT_STATE_SOURCES = [
    "client/State.cpp",
]

FIZZ_UTIL_PARSE_HEADERS = [
    "util/Parse-inl.h",
    "util/Parse.h",
]

FIZZ_CRYPTO_SHA_HEADERS = [
    "crypto/Sha-inl.h",
    "crypto/Sha.h",
]

FIZZ_CRYPTO_ASYMMETRIC_HEADERS = [
    "backend/openssl/crypto/ECCurve.h",
]

FIZZ_CLIENT_FIZZ_CLIENT_HEADERS = [
    "client/FizzClient-inl.h",
    "client/FizzClient.h",
]

FIZZ_CLIENT_ASYNC_FIZZ_CLIENT_HEADERS = [
    "client/AsyncFizzClient-inl.h",
    "client/AsyncFizzClient.h",
]

FIZZ_UTIL_VARIANT_HEADERS = [
    "util/Variant.h",
]

FIZZ_COMPRESSION_CERTIFICATE_COMPRESSOR_HEADERS = [
    "compression/CertificateCompressor.h",
]

FIZZ_COMPRESSION_CERT_DECOMPRESSION_MANAGER_HEADERS = [
    "compression/CertDecompressionManager.h",
]

FIZZ_COMPRESSION_CERT_DECOMPRESSION_MANAGER_SOURCES = [
    "compression/CertDecompressionManager.cpp",
]

FIZZ_COMPRESSION_ZLIB_CERTIFICATE_DECOMPRESSOR_HEADERS = [
    "compression/ZlibCertificateDecompressor.h",
]

FIZZ_COMPRESSION_ZLIB_CERTIFICATE_DECOMPRESSOR_SOURCES = [
    "compression/ZlibCertificateDecompressor.cpp",
]

FIZZ_COMPRESSION_ZSTD_CERTIFICATE_DECOMPRESSOR_HEADERS = [
    "compression/ZstdCertificateDecompressor.h",
]

FIZZ_COMPRESSION_ZSTD_CERTIFICATE_DECOMPRESSOR_SOURCES = [
    "compression/ZstdCertificateDecompressor.cpp",
]

# @unsorted-dict-items
XPLAT_FIZZ_SOURCE_MAP = {
    "FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_CONTEXT_HEADERS": FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_CONTEXT_HEADERS,
    "FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_SERVER_EXTENSION_HEADERS": FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_SERVER_EXTENSION_HEADERS,
    "FIZZ_SERVER_ASYNC_FIZZ_SERVER_HEADERS": FIZZ_SERVER_ASYNC_FIZZ_SERVER_HEADERS,
    "FIZZ_SERVER_TICKET_TYPES_HEADERS": FIZZ_SERVER_TICKET_TYPES_HEADERS,
    "FIZZ_PROTOCOL_DEFAULT_CERTIFICATE_VERIFIER_HEADERS": FIZZ_PROTOCOL_DEFAULT_CERTIFICATE_VERIFIER_HEADERS,
    "FIZZ_PROTOCOL_DEFAULT_CERTIFICATE_VERIFIER_SOURCES": FIZZ_PROTOCOL_DEFAULT_CERTIFICATE_VERIFIER_SOURCES,
    "FIZZ_SERVER_FIZZ_SERVER_CONTEXT_HEADERS": FIZZ_SERVER_FIZZ_SERVER_CONTEXT_HEADERS,
    "FIZZ_UTIL_FIZZ_UTIL_HEADERS": FIZZ_UTIL_FIZZ_UTIL_HEADERS,
    "FIZZ_UTIL_FIZZ_UTIL_SOURCES": FIZZ_UTIL_FIZZ_UTIL_SOURCES,
    "FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_HEADERS": FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_HEADERS,
    "FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_SOURCES": FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_SOURCES,
    "FIZZ_RECORD_RECORD_HEADERS": FIZZ_RECORD_RECORD_HEADERS,
    "FIZZ_RECORD_RECORD_SOURCES": FIZZ_RECORD_RECORD_SOURCES,
    "FIZZ_SERVER_NEGOTIATOR_HEADERS": FIZZ_SERVER_NEGOTIATOR_HEADERS,
    "FIZZ_SERVER_SERVER_EXTENSIONS_HEADERS": FIZZ_SERVER_SERVER_EXTENSIONS_HEADERS,
    "FIZZ_PROTOCOL_ASYNC_FIZZ_BASE_HEADERS": FIZZ_PROTOCOL_ASYNC_FIZZ_BASE_HEADERS,
    "FIZZ_PROTOCOL_ASYNC_FIZZ_BASE_SOURCES": FIZZ_PROTOCOL_ASYNC_FIZZ_BASE_SOURCES,
    "FIZZ_PROTOCOL_EXPORTER_HEADERS": FIZZ_PROTOCOL_EXPORTER_HEADERS,
    "FIZZ_PROTOCOL_EXPORTER_SOURCES": FIZZ_PROTOCOL_EXPORTER_SOURCES,
    "FIZZ_SERVER_FIZZ_SERVER_HEADERS": FIZZ_SERVER_FIZZ_SERVER_HEADERS,
    "FIZZ_SERVER_FIZZ_SERVER_SOURCES": FIZZ_SERVER_FIZZ_SERVER_SOURCES,
    "FIZZ_SERVER_PROTOCOL_HEADERS": FIZZ_SERVER_PROTOCOL_HEADERS,
    "FIZZ_SERVER_PROTOCOL_SOURCES": FIZZ_SERVER_PROTOCOL_SOURCES,
    "FIZZ_CRYPTO_AEAD_EVPCIPHER_HEADERS": FIZZ_CRYPTO_AEAD_EVPCIPHER_HEADERS,
    "FIZZ_CRYPTO_AEAD_EVPCIPHER_SOURCES": FIZZ_CRYPTO_AEAD_EVPCIPHER_SOURCES,
    "FIZZ_CRYPTO_HKDF_HEADERS": FIZZ_CRYPTO_HKDF_HEADERS,
    "FIZZ_CRYPTO_HKDF_SOURCES": FIZZ_CRYPTO_HKDF_SOURCES,
    "FIZZ_PROTOCOL_TYPES_HEADERS": FIZZ_PROTOCOL_TYPES_HEADERS,
    "FIZZ_PROTOCOL_TYPES_SOURCES": FIZZ_PROTOCOL_TYPES_SOURCES,
    "FIZZ_SERVER_AEAD_TICKET_CIPHER_HEADERS": FIZZ_SERVER_AEAD_TICKET_CIPHER_HEADERS,
    "FIZZ_SERVER_TICKET_CODEC_HEADERS": FIZZ_SERVER_TICKET_CODEC_HEADERS,
    "FIZZ_SERVER_TICKET_CODEC_SOURCES": FIZZ_SERVER_TICKET_CODEC_SOURCES,
    "FIZZ_PROTOCOL_CERTIFICATE_VERIFIER_HEADERS": FIZZ_PROTOCOL_CERTIFICATE_VERIFIER_HEADERS,
    "FIZZ_PROTOCOL_CERTIFICATE_HEADERS": FIZZ_PROTOCOL_CERTIFICATE_HEADERS,
    "FIZZ_PROTOCOL_CERTIFICATE_SOURCES": FIZZ_PROTOCOL_CERTIFICATE_SOURCES,
    "FIZZ_PROTOCOL_CLOCK_SYSTEM_CLOCK_HEADERS": FIZZ_PROTOCOL_CLOCK_SYSTEM_CLOCK_HEADERS,
    "FIZZ_PROTOCOL_CLOCK_SYSTEM_CLOCK_SOURCES": FIZZ_PROTOCOL_CLOCK_SYSTEM_CLOCK_SOURCES,
    "FIZZ_PROTOCOL_OPENSSL_FACTORY_HEADERS": FIZZ_PROTOCOL_OPENSSL_FACTORY_HEADERS,
    "FIZZ_SERVER_CERT_MANAGER_HEADERS": FIZZ_SERVER_CERT_MANAGER_HEADERS,
    "FIZZ_SERVER_CERT_MANAGER_SOURCES": FIZZ_SERVER_CERT_MANAGER_SOURCES,
    "FIZZ_SERVER_COOKIE_CIPHER_HEADERS": FIZZ_SERVER_COOKIE_CIPHER_HEADERS,
    "FIZZ_SERVER_COOKIE_CIPHER_SOURCES": FIZZ_SERVER_COOKIE_CIPHER_SOURCES,
    "FIZZ_SERVER_AEAD_COOKIE_CIPHER_HEADERS": FIZZ_SERVER_AEAD_COOKIE_CIPHER_HEADERS,
    "FIZZ_SERVER_AEAD_COOKIE_CIPHER_SOURCES": FIZZ_SERVER_AEAD_COOKIE_CIPHER_SOURCES,
    "FIZZ_SERVER_REPLAY_CACHE_HEADERS": FIZZ_SERVER_REPLAY_CACHE_HEADERS,
    "FIZZ_SERVER_REPLAY_CACHE_SOURCES": FIZZ_SERVER_REPLAY_CACHE_SOURCES,
    "FIZZ_SERVER_TICKET_CIPHER_HEADERS": FIZZ_SERVER_TICKET_CIPHER_HEADERS,
    "FIZZ_PROTOCOL_KEY_SCHEDULER_HEADERS": FIZZ_PROTOCOL_KEY_SCHEDULER_HEADERS,
    "FIZZ_PROTOCOL_KEY_SCHEDULER_SOURCES": FIZZ_PROTOCOL_KEY_SCHEDULER_SOURCES,
    "FIZZ_CRYPTO_KEY_DERIVATION_HEADERS": FIZZ_CRYPTO_KEY_DERIVATION_HEADERS,
    "FIZZ_CRYPTO_KEY_DERIVATION_SOURCES": FIZZ_CRYPTO_KEY_DERIVATION_SOURCES,
    "FIZZ_PROTOCOL_FACTORY_HEADERS": FIZZ_PROTOCOL_FACTORY_HEADERS,
    "FIZZ_PROTOCOL_FIZZ_BASE_HEADERS": FIZZ_PROTOCOL_FIZZ_BASE_HEADERS,
    "FIZZ_CRYPTO_UTILS_HEADERS": FIZZ_CRYPTO_UTILS_HEADERS,
    "FIZZ_CRYPTO_UTILS_SOURCES": FIZZ_CRYPTO_UTILS_SOURCES,
    "FIZZ_PROTOCOL_ACTIONS_HEADERS": FIZZ_PROTOCOL_ACTIONS_HEADERS,
    "FIZZ_PROTOCOL_PARAMS_HEADERS": FIZZ_PROTOCOL_PARAMS_HEADERS,
    "FIZZ_PROTOCOL_PROTOCOL_HEADERS": FIZZ_PROTOCOL_PROTOCOL_HEADERS,
    "FIZZ_PROTOCOL_STATE_MACHINE_HEADERS": FIZZ_PROTOCOL_STATE_MACHINE_HEADERS,
    "FIZZ_RECORD_PLAINTEXT_RECORD_LAYER_HEADERS": FIZZ_RECORD_PLAINTEXT_RECORD_LAYER_HEADERS,
    "FIZZ_RECORD_PLAINTEXT_RECORD_LAYER_SOURCES": FIZZ_RECORD_PLAINTEXT_RECORD_LAYER_SOURCES,
    "FIZZ_RECORD_RECORD_LAYER_HEADERS": FIZZ_RECORD_RECORD_LAYER_HEADERS,
    "FIZZ_RECORD_RECORD_LAYER_SOURCES": FIZZ_RECORD_RECORD_LAYER_SOURCES,
    "FIZZ_SERVER_ASYNC_SELF_CERT_HEADERS": FIZZ_SERVER_ASYNC_SELF_CERT_HEADERS,
    "FIZZ_SERVER_RESUMPTION_STATE_HEADERS": FIZZ_SERVER_RESUMPTION_STATE_HEADERS,
    "FIZZ_UTIL_WORKAROUNDS_HEADERS": FIZZ_UTIL_WORKAROUNDS_HEADERS,
    "FIZZ_CRYPTO_AEAD_AEAD_HEADERS": FIZZ_CRYPTO_AEAD_AEAD_HEADERS,
    "FIZZ_CRYPTO_AEAD_IOBUF_HEADERS": FIZZ_CRYPTO_AEAD_IOBUF_HEADERS,
    "FIZZ_CRYPTO_AEAD_IOBUF_SOURCES": FIZZ_CRYPTO_AEAD_IOBUF_SOURCES,
    "FIZZ_SERVER_TOKEN_CIPHER_HEADERS": FIZZ_SERVER_TOKEN_CIPHER_HEADERS,
    "FIZZ_SERVER_AEAD_TOKEN_CIPHER_HEADERS": FIZZ_SERVER_AEAD_TOKEN_CIPHER_HEADERS,
    "FIZZ_SERVER_AEAD_TOKEN_CIPHER_SOURCES": FIZZ_SERVER_AEAD_TOKEN_CIPHER_SOURCES,
    "FIZZ_CRYPTO_SIGNATURE_SIGNATURE_HEADERS": FIZZ_CRYPTO_SIGNATURE_SIGNATURE_HEADERS,
    "FIZZ_CRYPTO_SIGNATURE_SIGNATURE_SOURCES": FIZZ_CRYPTO_SIGNATURE_SIGNATURE_SOURCES,
    "FIZZ_PROTOCOL_CLOCK_CLOCK_HEADERS": FIZZ_PROTOCOL_CLOCK_CLOCK_HEADERS,
    "FIZZ_CRYPTO_HMAC_SHA256_HEADERS": FIZZ_CRYPTO_HMAC_SHA256_HEADERS,
    "FIZZ_CRYPTO_HMAC_SHA256_SOURCES": FIZZ_CRYPTO_HMAC_SHA256_SOURCES,
    "FIZZ_CRYPTO_HMAC_SHA384_HEADERS": FIZZ_CRYPTO_HMAC_SHA384_HEADERS,
    "FIZZ_CRYPTO_HMAC_SHA384_SOURCES": FIZZ_CRYPTO_HMAC_SHA384_SOURCES,
    "FIZZ_CRYPTO_HMAC_SHA512_HEADERS": FIZZ_CRYPTO_HMAC_SHA512_HEADERS,
    "FIZZ_CRYPTO_HMAC_SHA512_SOURCES": FIZZ_CRYPTO_HMAC_SHA512_SOURCES,
    "FIZZ_PROTOCOL_HANDSHAKE_CONTEXT_HEADERS": FIZZ_PROTOCOL_HANDSHAKE_CONTEXT_HEADERS,
    "FIZZ_CRYPTO_EXCHANGE_EXCHANGE_HEADERS": FIZZ_CRYPTO_EXCHANGE_EXCHANGE_HEADERS,
    "FIZZ_CRYPTO_EXCHANGE_KEY_EXCHANGE_HEADERS": FIZZ_CRYPTO_EXCHANGE_KEY_EXCHANGE_HEADERS,
    "FIZZ_CRYPTO_EXCHANGE_X25519_HEADERS": FIZZ_CRYPTO_EXCHANGE_X25519_HEADERS,
    "FIZZ_CRYPTO_EXCHANGE_X25519_SOURCES": FIZZ_CRYPTO_EXCHANGE_X25519_SOURCES,
    "FIZZ_CRYPTO_RANDOM_HEADERS": FIZZ_CRYPTO_RANDOM_HEADERS,
    "FIZZ_RECORD_ENCRYPTED_RECORD_LAYER_HEADERS": FIZZ_RECORD_ENCRYPTED_RECORD_LAYER_HEADERS,
    "FIZZ_RECORD_ENCRYPTED_RECORD_LAYER_SOURCES": FIZZ_RECORD_ENCRYPTED_RECORD_LAYER_SOURCES,
    "FIZZ_RECORD_BUF_AND_PADDING_POLICY_HEADERS": FIZZ_RECORD_BUF_AND_PADDING_POLICY_HEADERS,
    "FIZZ_RECORD_BUF_AND_PADDING_POLICY_SOURCES": FIZZ_RECORD_BUF_AND_PADDING_POLICY_SOURCES,
    "FIZZ_CLIENT_PSK_SERIALIZATION_HEADERS": FIZZ_CLIENT_PSK_SERIALIZATION_HEADERS,
    "FIZZ_CLIENT_PSK_SERIALIZATION_SOURCES": FIZZ_CLIENT_PSK_SERIALIZATION_SOURCES,
    "FIZZ_CLIENT_CLIENT_EXTENSIONS_HEADERS": FIZZ_CLIENT_CLIENT_EXTENSIONS_HEADERS,
    "FIZZ_CLIENT_PSK_CACHE_HEADERS": FIZZ_CLIENT_PSK_CACHE_HEADERS,
    "FIZZ_PROTOCOL_EVENTS_HEADERS": FIZZ_PROTOCOL_EVENTS_HEADERS,
    "FIZZ_PROTOCOL_EVENTS_SOURCES": FIZZ_PROTOCOL_EVENTS_SOURCES,
    "FIZZ_BACKEND_BACKEND_HEADERS": FIZZ_BACKEND_BACKEND_HEADERS,
    "FIZZ_CRYPTO_OPENSSL_OPENSSL_HEADERS": FIZZ_CRYPTO_OPENSSL_OPENSSL_HEADERS,
    "FIZZ_CRYPTO_OPENSSL_OPENSSL_SOURCES": FIZZ_CRYPTO_OPENSSL_OPENSSL_SOURCES,
    "FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_CLIENT_EXTENSION_HEADERS": FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_CLIENT_EXTENSION_HEADERS,
    "FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_CLIENT_EXTENSION_SOURCES": FIZZ_EXTENSIONS_TOKENBINDING_TOKEN_BINDING_CLIENT_EXTENSION_SOURCES,
    "FIZZ_CLIENT_EARLY_DATA_REJECTION_HEADERS": FIZZ_CLIENT_EARLY_DATA_REJECTION_HEADERS,
    "FIZZ_CLIENT_EARLY_DATA_REJECTION_SOURCES": FIZZ_CLIENT_EARLY_DATA_REJECTION_SOURCES,
    "FIZZ_CLIENT_PROTOCOL_HEADERS": FIZZ_CLIENT_PROTOCOL_HEADERS,
    "FIZZ_CLIENT_PROTOCOL_SOURCES": FIZZ_CLIENT_PROTOCOL_SOURCES,
    "FIZZ_CLIENT_ACTIONS_HEADERS": FIZZ_CLIENT_ACTIONS_HEADERS,
    "FIZZ_CLIENT_FIZZ_CLIENT_CONTEXT_HEADERS": FIZZ_CLIENT_FIZZ_CLIENT_CONTEXT_HEADERS,
    "FIZZ_CLIENT_STATE_HEADERS": FIZZ_CLIENT_STATE_HEADERS,
    "FIZZ_CLIENT_STATE_SOURCES": FIZZ_CLIENT_STATE_SOURCES,
    "FIZZ_UTIL_PARSE_HEADERS": FIZZ_UTIL_PARSE_HEADERS,
    "FIZZ_CRYPTO_SHA_HEADERS": FIZZ_CRYPTO_SHA_HEADERS,
    "FIZZ_CRYPTO_ASYMMETRIC_HEADERS": FIZZ_CRYPTO_ASYMMETRIC_HEADERS,
    "FIZZ_CLIENT_FIZZ_CLIENT_HEADERS": FIZZ_CLIENT_FIZZ_CLIENT_HEADERS,
    "FIZZ_CLIENT_ASYNC_FIZZ_CLIENT_HEADERS": FIZZ_CLIENT_ASYNC_FIZZ_CLIENT_HEADERS,
    "FIZZ_UTIL_VARIANT_HEADERS": FIZZ_UTIL_VARIANT_HEADERS,
    "FIZZ_COMPRESSION_CERTIFICATE_COMPRESSOR_HEADERS": FIZZ_COMPRESSION_CERTIFICATE_COMPRESSOR_HEADERS,
    "FIZZ_COMPRESSION_CERT_DECOMPRESSION_MANAGER_HEADERS": FIZZ_COMPRESSION_CERT_DECOMPRESSION_MANAGER_HEADERS,
    "FIZZ_COMPRESSION_CERT_DECOMPRESSION_MANAGER_SOURCES": FIZZ_COMPRESSION_CERT_DECOMPRESSION_MANAGER_SOURCES,
    "FIZZ_COMPRESSION_ZLIB_CERTIFICATE_DECOMPRESSOR_HEADERS": FIZZ_COMPRESSION_ZLIB_CERTIFICATE_DECOMPRESSOR_HEADERS,
    "FIZZ_COMPRESSION_ZLIB_CERTIFICATE_DECOMPRESSOR_SOURCES": FIZZ_COMPRESSION_ZLIB_CERTIFICATE_DECOMPRESSOR_SOURCES,
    "FIZZ_COMPRESSION_ZSTD_CERTIFICATE_DECOMPRESSOR_HEADERS": FIZZ_COMPRESSION_ZSTD_CERTIFICATE_DECOMPRESSOR_HEADERS,
    "FIZZ_COMPRESSION_ZSTD_CERTIFICATE_DECOMPRESSOR_SOURCES": FIZZ_COMPRESSION_ZSTD_CERTIFICATE_DECOMPRESSOR_SOURCES,
}
