load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("secure_pipes")

cpp_library(
    name = "mocks",
    headers = [
        "Mocks.h",
    ],
    exported_deps = [
        "//fizz/crypto/aead:aead",
        "//folly/portability:gmock",
    ],
)

cpp_library(
    name = "data",
    headers = [
        "Data.h",
    ],
    exported_deps = [
        "//fizz/record:record",
    ],
)

cpp_library(
    name = "test_util",
    srcs = [
        "TestUtil.cpp",
    ],
    headers = [
        "TestUtil.h",
    ],
    deps = [
        "//fizz/crypto/aead:iobuf",
    ],
    exported_deps = [
        "//folly:memory",
        "//folly:string",
        "//folly/io:iobuf",
    ],
)

cpp_unittest(
    name = "util_test",
    srcs = [
        "IOBufUtilTest.cpp",
    ],
    deps = [
        "//fizz/crypto/aead:iobuf",
        "//folly/io:iobuf",
        "//folly/portability:gtest",
    ],
)
