load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("secure_pipes")

cpp_library(
    name = "clock",
    headers = [
        "Clock.h",
    ],
)

cpp_library(
    name = "system_clock",
    srcs = [
        "SystemClock.cpp",
    ],
    headers = [
        "SystemClock.h",
    ],
    exported_deps = [
        ":clock",
    ],
)
