load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")

oncall("secure_pipes")

python_binary(
    # @autodeps-skip
    name = "fizz_trace",
    srcs = [
        "fizztrace.py",
    ],
    main_function = "fizz.facebook.debug.fizztrace.main",
    deps = [
        "fbsource//third-party/bcc:bcc-py",
        "fbsource//third-party/bcc:libbcc",
    ],
)
