load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("secure_pipes")

cpp_library(
    name = "oqs_key_exchange",
    srcs = [
        "OQSKeyExchange.cpp",
    ],
    headers = [
        "OQSKeyExchange.h",
    ],
    exported_deps = [
        "fbsource//third-party/liboqs:oqs",
        "//fizz/crypto/exchange:key_exchange",
        "//folly:memory",
    ],
)
