load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("secure_pipes")

cpp_unittest(
    name = "fizz_util_test",
    srcs = [
        "FizzUtilTest.cpp",
    ],
    deps = [
        "//fizz/crypto/test:TestUtil",
        "//fizz/protocol/clock/test:mock_clock",
        "//fizz/protocol/test:mocks",
        "//fizz/server:ticket_types",
        "//fizz/util:fizz_util",
        "//folly:file_util",
        "//folly/experimental:test_util",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "variant_test",
    srcs = [
        "FizzVariantTest.cpp",
    ],
    deps = [
        "//fizz/util:variant",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "key_log_writer_test",
    srcs = [
        "KeyLogWriterTest.cpp",
    ],
    deps = [
        "//fizz/crypto:random",
        "//fizz/util:key_log_writer",
        "//folly/portability:gtest",
    ],
)
