load("@fbsource//xplat/fizz:defs.bzl", "fizz_cpp_unittest")

oncall("secure_pipes")

fizz_cpp_unittest(
    name = "hmac_test",
    srcs = [
        "Hmac.cpp",
    ],
    deps = [
        "//fizz/backend:openssl",
        "//fizz/crypto/test:HmacTest",
        "//folly/portability:gtest",
    ],
)

fizz_cpp_unittest(
    name = "key_utils",
    srcs = [
        "OpenSSLKeyUtilsTest.cpp",
    ],
    deps = [
        "//fizz/backend:openssl",
        "//fizz/crypto/test:TestUtil",
        "//folly/portability:gtest",
    ],
)
