load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("secure_pipes")

cpp_unittest(
    name = "batch_signature_async_self_cert_test",
    srcs = [
        "BatchSignatureAsyncSelfCertTest.cpp",
    ],
    deps = [
        "//fizz/backend:openssl",
        "//fizz/crypto/test:TestUtil",
        "//fizz/experimental/batcher:batcher",
        "//fizz/experimental/server:batch_signature_async_self_cert",
        "//fizz/protocol/test:mocks",
        "//fizz/server/test:mocks",
        "//folly/portability:gtest",
    ],
)
