load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("secure_pipes")

cpp_unittest(
    name = "batch_signature_types_test",
    srcs = [
        "BatchSignatureTypesTest.cpp",
    ],
    deps = [
        "//fizz/experimental/protocol:batch_signature_types",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)
