load("@fbsource//xplat/fizz:defs.bzl", "fizz_cpp_unittest")

oncall("secure_pipes")

fizz_cpp_unittest(
    name = "oqs_key_exchange_test",
    srcs = [
        "OQSKeyExchangeTest.cpp",
    ],
    deps = [
        "//fizz/backend:liboqs",
        "//fizz/util:status",
        "//folly/portability:gtest",
    ],
)
