load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")

oncall("mobile_networking_core")

fb_native.constraint_setting(
    name = "profile",
    visibility = ["PUBLIC"],
)

# Uses MNS crypto instead of OpenSSL certificate dependencies
fb_native.constraint_value(
    name = "mnscrypto-only",
    constraint_setting = ":profile",
    visibility = ["PUBLIC"],
)

fb_native.constraint_value(
    name = "xplat",
    constraint_setting = ":profile",
    visibility = ["PUBLIC"],
)

fb_native.constraint_setting(
    name = "oqs",
    visibility = ["PUBLIC"],
)

# Constrain a platform to not use liboqs-related components in Fizz
fb_native.constraint_value(
    name = "oqs-disabled",
    constraint_setting = ":oqs",
    visibility = ["PUBLIC"],
)

fb_native.constraint_setting(
    name = "fizzy-factory-setting",
    visibility = ["PUBLIC"],
)

fb_native.constraint_value(
    name = "fizzy-user-must-set-factory-explicitly",
    constraint_setting = ":fizzy-factory-setting",
    visibility = ["PUBLIC"],
)
