load("@prelude//configurations:constraint_alias.bzl", "constraint_with_aliases")

oncall("mobile_networking_platform")

constraint_with_aliases(
    name = "profile",
    aliases = {
        "mnscrypto-only": "mnscrypto-only",
        "xplat": "xplat",
    },
    default = "unspecified",
    values = [
        "mnscrypto-only",
        "xplat",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)

constraint_with_aliases(
    name = "oqs",
    aliases = {
        "oqs-disabled": "disabled",
    },
    default = "unspecified",
    values = [
        "disabled",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)

constraint_with_aliases(
    name = "fizzy-factory-setting",
    aliases = {
        "fizzy-user-must-set-factory-explicitly": "user-must-set-factory-explicitly",
    },
    default = "unspecified",
    values = [
        "user-must-set-factory-explicitly",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)
