load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("secure_pipes")

cpp_library(
    name = "mock_clock",
    headers = [
        "Mocks.h",
    ],
    exported_deps = [
        "//fizz/protocol/clock:clock",
        "//folly/portability:gmock",
    ],
)
