load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("secure_pipes")

cpp_unittest(
    name = "token_binding_test",
    srcs = [
        "TokenBindingTest.cpp",
    ],
    deps = [
        "//fizz/extensions/tokenbinding:token_binding",
        "//fizz/extensions/tokenbinding:token_binding_context",
        "//fizz/record:record",
        "//fizz/record/test:extension_tests_base",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "token_binding_server_extension_test",
    srcs = [
        "TokenBindingServerExtensionTest.cpp",
    ],
    deps = [
        "//fizz/extensions/tokenbinding:token_binding",
        "//fizz/extensions/tokenbinding:token_binding_context",
        "//fizz/extensions/tokenbinding:token_binding_server_extension",
        "//fizz/record:record",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "validator_test",
    srcs = [
        "ValidatorTest.cpp",
    ],
    deps = [
        "//fizz/extensions/tokenbinding:token_binding",
        "//fizz/extensions/tokenbinding:token_binding_validator",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "token_binding_client_extension_test",
    srcs = [
        "TokenBindingClientExtensionTest.cpp",
    ],
    deps = [
        "//fizz/extensions/tokenbinding:token_binding_client_extension",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "token_binding_constructor_test",
    srcs = [
        "TokenBindingConstructorTest.cpp",
    ],
    deps = [
        "//fizz/extensions/tokenbinding:token_binding_constructor",
        "//fizz/extensions/tokenbinding:token_binding_validator",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)
