load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("secure_pipes")

cpp_library(
    name = "java_crypto",
    srcs = [
        "JavaCryptoCertificateVerifier.cpp",
        "JavaCryptoPeerCert.cpp",
        "JniUtils.cpp",
        "OnLoad.cpp",
    ],
    headers = [
        "JavaCryptoCertificateVerifier.h",
        "JavaCryptoFactory.h",
        "JavaCryptoPeerCert.h",
        "JniUtils.h",
    ],
    # This library uses proxygen, which hasn't been modularized yet, so keep
    # using textual inclusion for now.
    modular_headers = False,
    deps = [
        "//folly/ssl:openssl_cert_utils",
    ],
    exported_deps = [
        "fbsource//third-party/jvm:jvm",
        "//fizz/backend:openssl",
        "//fizz/protocol:certificate",
        "//fizz/protocol:certificate_verifier",
        "//fizz/protocol:default_factory",
        "//fizz/record:record",
        "//folly:range",
    ],
    external_deps = [
        "glog",
    ],
)
