load("@fbsource//tools/build_defs:default_platform_defs.bzl", "get_host_target_platform")
load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")

oncall("mobile_networking_core")

deps = [x for x in [get_host_target_platform()] if x != None]

fb_native.platform(
    name = "fizz-mobile",
    constraint_values = [
        "fbsource//xplat/fizz/constraints:mnscrypto-only",
    ],
    visibility = ["PUBLIC"],
    deps = deps,
)

fb_native.platform(
    name = "fizz-mobile-keep-openssl",
    constraint_values = [
        "fbsource//xplat/fizz/constraints:fizzy-user-must-set-factory-explicitly",
    ],
    visibility = ["PUBLIC"],
    deps = deps,
)
