load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("secure_pipes")

cpp_library(
    name = "batcher",
    headers = [
        "Batcher.h",
    ],
    exported_deps = [
        "//fizz/experimental/crypto:batch_signature",
        "//fizz/experimental/protocol:batch_signature_types",
        "//fizz/server:async_self_cert",
        "//folly/futures:shared_promise",
    ],
)
