load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("secure_pipes")

cpp_unittest(
    name = "cert_utils_test",
    srcs = ["CertUtilsTest.cpp"],
    deps = [
        "//fizz/backend:openssl",
        "//fizz/protocol/test:cert_test_types",
        "//folly/portability:gtest",
    ],
)
