load("@fbsource//xplat/fizz:defs.bzl", "fizz_cpp_unittest")

oncall("secure_pipes")

fizz_cpp_unittest(
    name = "cert_utils_test",
    srcs = ["CertUtilsTest.cpp"],
    deps = [
        "//fizz/backend:openssl",
        "//fizz/protocol/test:cert_test_types",
        "//folly/portability:gtest",
    ],
)

fizz_cpp_unittest(
    name = "openssl_certificate_verifier_test",
    srcs = [
        "OpenSSLCertificateVerifierTest.cpp",
    ],
    deps = [
        "//fizz/backend:openssl",
        "//fizz/protocol/test:cert_util",
        "//folly/portability:gtest",
        "//folly/ssl:openssl_cert_utils",
    ],
)
