load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("secure_pipes")

cpp_unittest(
    name = "ec",
    srcs = [
        "ECSignatureTest.cpp",
    ],
    supports_static_listing = False,
    deps = [
        "//fizz/backend:openssl",
        "//folly:string",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "ed",
    srcs = [
        "EdSignatureTest.cpp",
    ],
    headers = [
        "EdSignatureTest.h",
    ],
    supports_static_listing = False,
    deps = [
        "//fizz/backend:openssl",
        "//fizz/crypto/test:TestUtil",
        "//folly:fixed_string",
        "//folly:string",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "rsa_pss",
    srcs = [
        "RSAPSSSignatureTest.cpp",
    ],
    deps = [
        "//fizz/backend:openssl",
        "//folly/portability:gtest",
    ],
)
