load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("secure_pipes")

cpp_unittest(
    name = "fizz_command_common",
    srcs = [
        "FizzCommandCommonTest.cpp",
    ],
    deps = [
        "//fizz/protocol/ech:encrypted_client_hello",
        "//fizz/tool:tool_lib",
        "//folly/container:array",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)
