load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("secure_pipes")

cpp_library(
    name = "cert_extraction",
    srcs = [],
    headers = [
        "CertExtraction.h",
    ],
    deps = [
    ],
    exported_deps = [
        "//fizz/client:async_fizz_client",
        "//fizz/server:async_fizz_server",
    ],
)
