load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("secure_pipes")

cpp_unittest(
    name = "merkle_tree_test",
    srcs = [
        "MerkleTreeTest.cpp",
    ],
    deps = [
        "//fizz/backend:openssl",
        "//fizz/crypto/test:TestUtil",
        "//fizz/experimental/crypto:merkle_tree",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "batch_signature_test",
    srcs = [
        "BatchSignatureTest.cpp",
    ],
    deps = [
        "//fizz/crypto/test:TestUtil",
        "//fizz/experimental/crypto:batch_signature",
        "//folly/io:iobuf",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "oqs_key_exchange_test",
    srcs = [
        "OQSKeyExchangeTest.cpp",
    ],
    deps = [
        "//fizz/experimental/crypto/exchange:oqs_key_exchange",
        "//folly/portability:gtest",
    ],
)
