load("@fbsource//xplat/fizz:defs.bzl", "fizz_cpp_unittest")

oncall("secure_pipes")

fizz_cpp_unittest(
    name = "merkle_tree_test",
    srcs = [
        "MerkleTreeTest.cpp",
    ],
    deps = [
        "//fizz/backend:openssl",
        "//fizz/crypto/test:TestUtil",
        "//fizz/experimental/crypto:merkle_tree",
        "//folly/portability:gtest",
    ],
)

fizz_cpp_unittest(
    name = "batch_signature_test",
    srcs = [
        "BatchSignatureTest.cpp",
    ],
    deps = [
        "//fizz/crypto/test:TestUtil",
        "//fizz/experimental/crypto:batch_signature",
        "//folly/io:iobuf",
        "//folly/portability:gtest",
    ],
)
