load("@fbsource//xplat/fizz:defs.bzl", "fizz_cpp_unittest")

oncall("secure_pipes")

fizz_cpp_unittest(
    name = "ECKey",
    srcs = [
        "ECKeyExchangeTest.cpp",
    ],
    supports_static_listing = False,
    deps = [
        "//fizz/backend:openssl",
        "//fizz/crypto/test:TestKeys",
        "//fizz/crypto/test:TestUtil",
        "//fizz/util:status",
        "//folly:string",
        "//folly/portability:gtest",
        "//folly/ssl:openssl_ptr_types",
    ],
    external_deps = [
        ("openssl", None, "crypto"),
    ],
)

fizz_cpp_unittest(
    name = "OpenSSLKemKeyExchange",
    srcs = [
        "OpenSSLKemKeyExchangeTest.cpp",
    ],
    supports_static_listing = False,
    deps = [
        "//fizz/backend:openssl",
        "//fizz/protocol:default_factory",
        "//fizz/record:record",
        "//fizz/util:status",
        "//folly/portability:gtest",
    ],
    external_deps = [
        ("openssl", None, "crypto"),
    ],
)
