load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("secure_pipes")

cpp_library(
    name = "batch_signature_peer_cert",
    srcs = [
        "BatchSignaturePeerCert.cpp",
    ],
    headers = [
        "BatchSignaturePeerCert.h",
    ],
    exported_deps = [
        "//fizz/experimental/crypto:batch_signature",
        "//fizz/experimental/protocol:batch_signature_types",
        "//fizz/protocol:certificate",
    ],
)
