load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("secure_pipes")

cpp_unittest(
    name = "exported_authenticator_test",
    srcs = [
        "ExportedAuthenticatorTest.cpp",
    ],
    deps = [
        "//fizz/backend:openssl",
        "//fizz/crypto/test:TestUtil",
        "//fizz/extensions/exportedauth:exported_authenticator",
        "//fizz/protocol:default_factory",
        "//fizz/protocol/test:mocks",
        "//fizz/protocol/test:test_util",
        "//fizz/record:record",
        "//folly:string",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)
